export const questions = [
  { question: "What is 17 × 6?", answers: ["92", "96", "102", "106"], correct: 2 },
  { question: "What is 25% of 240?", answers: ["50", "60", "70", "80"], correct: 1 },
  { question: "What is 144 ÷ 9?", answers: ["14", "15", "16", "18"], correct: 2 },
  { question: "What is 13²?", answers: ["149", "156", "169", "176"], correct: 2 },
  { question: "What is 7 × (15 − 3)?", answers: ["72", "78", "84", "90"], correct: 2 },
  { question: "What is 360 ÷ 12?", answers: ["24", "30", "36", "40"], correct: 1 },
  { question: "What is 18% of 200?", answers: ["30", "36", "40", "45"], correct: 1 },
  { question: "What is 9³?", answers: ["81", "243", "729", "656"], correct: 1 },
  { question: "What is 45 × 2 − 10?", answers: ["70", "75", "80", "85"], correct: 2 },
  { question: "What is 1.5 × 80?", answers: ["100", "110", "120", "130"], correct: 2 },

  // 🇮🇳 India States & Capitals (10)
  { question: "Capital of Chhattisgarh?", answers: ["Bilaspur", "Raipur", "Durg", "Korba"], correct: 1 },
  { question: "Capital of Jharkhand?", answers: ["Bokaro", "Dhanbad", "Ranchi", "Jamshedpur"], correct: 2 },
  { question: "Capital of Sikkim?", answers: ["Gangtok", "Namchi", "Pelling", "Mangan"], correct: 0 },
  { question: "Capital of Himachal Pradesh?", answers: ["Manali", "Shimla", "Solan", "Kullu"], correct: 1 },
  { question: "Capital of Mizoram?", answers: ["Aizawl", "Lunglei", "Champhai", "Serchhip"], correct: 0 },
  { question: "Capital of Nagaland?", answers: ["Dimapur", "Kohima", "Mon", "Wokha"], correct: 1 },
  { question: "Capital of Uttarakhand?", answers: ["Haridwar", "Rishikesh", "Dehradun", "Nainital"], correct: 2 },
  { question: "Capital of Arunachal Pradesh?", answers: ["Tawang", "Ziro", "Itanagar", "Pasighat"], correct: 2 },
  { question: "Capital of Odisha?", answers: ["Puri", "Cuttack", "Bhubaneswar", "Rourkela"], correct: 2 },
  { question: "Capital of Meghalaya?", answers: ["Shillong", "Tura", "Jowai", "Nongpoh"], correct: 0 },

  // 🎬 Bollywood (10)
  { question: "Who directed Lagaan?", answers: ["Karan Johar", "Ashutosh Gowariker", "Rajkumar Hirani", "Imtiaz Ali"], correct: 1 },
  { question: "Which movie starred Aamir Khan as a wrestler?", answers: ["Sultan", "Mary Kom", "Dangal", "Gold"], correct: 2 },
  { question: "Which actress debuted in Student of the Year?", answers: ["Kriti Sanon", "Alia Bhatt", "Ananya Panday", "Kiara Advani"], correct: 1 },
  { question: "Which film is about space scientists?", answers: ["PK", "Rocketry", "Mission Mangal", "Swades"], correct: 2 },
  { question: "Who played Munna Bhai?", answers: ["Sanjay Dutt", "Anil Kapoor", "Nana Patekar", "Ajay Devgn"], correct: 0 },
  { question: "Which movie has character Rancho?", answers: ["PK", "3 Idiots", "Taare Zameen Par", "Sanju"], correct: 1 },
  { question: "Who is known as Khiladi Kumar?", answers: ["Salman Khan", "Akshay Kumar", "Ajay Devgn", "Suniel Shetty"], correct: 1 },
  { question: "Which movie is based on Sanjay Dutt’s life?", answers: ["Sanju", "Rockstar", "Guru", "Agneepath"], correct: 0 },
  { question: "Which actress played Mastani?", answers: ["Priyanka Chopra", "Deepika Padukone", "Katrina Kaif", "Sonam Kapoor"], correct: 1 },
  { question: "Which film won Oscar for song 'Jai Ho'?", answers: ["Lagaan", "Slumdog Millionaire", "Swades", "Guru"], correct: 1 },

  // 🎭 Complete Bollywood Dialogues (10)
  { question: "Complete: 'Mere paas ___ hai.'", answers: ["Bangla", "Gaadi", "Maa", "Paisa"], correct: 2 },
  { question: "Complete: 'Picture abhi ___ hai.'", answers: ["baaki", "baki", "shuru", "chal rahi"], correct: 0 },
  { question: "Complete: 'Don ko pakadna mushkil hi nahi, ___ hai.'", answers: ["naamumkin", "namumkin hai", "impossible", "mushkil"], correct: 1 },
  { question: "Complete: 'Pushpa, I hate ___.'", answers: ["tears", "lies", "sorry", "you"], correct: 1 },
  { question: "Complete: 'Kitne aadmi ___?'", answers: ["the", "hai", "thhe", "hain"], correct: 2 },
  { question: "Complete: 'Bade bade deshon mein chhoti chhoti ___ hoti rehti hai.'", answers: ["baatein", "galtiyan", "cheez", "problems"], correct: 1 },
  { question: "Complete: 'Kabhi kabhi jeetne ke liye ___ bhi zaroori hota hai.'", answers: ["jeena", "ladna", "harna", "marna"], correct: 2 },
  { question: "Complete: 'Hum jahan khade hote hain, ___ wahi se shuru hoti hai.'", answers: ["line", "duniya", "competition", "kahani"], correct: 2 },
  { question: "Complete: 'Ek chutki sindoor ki keemat tum kya ___.'", answers: ["samjhoge", "jaano", "sochoge", "samjho"], correct: 0 },
  { question: "Complete: 'Aaj mere paas sab kuch hai, phir bhi ___.'", answers: ["akela hoon", "khush hoon", "dukhi hoon", "kuch nahi"], correct: 3 },

  // 🌍 Difficult Geography (10)
  { question: "Which is the longest river in India?", answers: ["Yamuna", "Ganga", "Godavari", "Brahmaputra"], correct: 1 },
  { question: "Which Indian state has the longest coastline?", answers: ["Tamil Nadu", "Andhra Pradesh", "Maharashtra", "Gujarat"], correct: 3 },
  { question: "Which plateau is called the 'Roof of the World'?", answers: ["Deccan", "Tibetan", "Chotanagpur", "Iranian"], correct: 1 },
  { question: "Which desert lies mostly in India?", answers: ["Gobi", "Kalahari", "Thar", "Sahara"], correct: 2 },
  { question: "Which pass connects India to Tibet?", answers: ["Rohtang", "Nathu La", "Zoji La", "Shipki La"], correct: 1 },
  { question: "Which sea lies to the south of India?", answers: ["Arabian Sea", "Bay of Bengal", "Indian Ocean", "Red Sea"], correct: 2 },
  { question: "Which is the largest freshwater lake in India?", answers: ["Dal Lake", "Wular Lake", "Chilika", "Sambhar"], correct: 1 },
  { question: "Which mountain range separates India from Central Asia?", answers: ["Aravalli", "Himalayas", "Vindhya", "Satpura"], correct: 1 },
  { question: "Which Indian state receives highest rainfall?", answers: ["Assam", "Meghalaya", "Kerala", "Arunachal Pradesh"], correct: 1 },
  { question: "Which river is called Dakshin Ganga?", answers: ["Krishna", "Godavari", "Kaveri", "Narmada"], correct: 1 },

  // 🕉️ Indian Mythology (10)
  { question: "Who wrote the Ramayana?", answers: ["Ved Vyasa", "Valmiki", "Tulsidas", "Kalidasa"], correct: 1 },
  { question: "Who was Arjuna’s charioteer?", answers: ["Krishna", "Balarama", "Bhishma", "Karna"], correct: 0 },
  { question: "Who is the wife of Lord Rama?", answers: ["Radha", "Sita", "Draupadi", "Parvati"], correct: 1 },
  { question: "Who had the boon of immortality?", answers: ["Karna", "Ravana", "Hanuman", "Ashwatthama"], correct: 3 },
  { question: "Which demon king had ten heads?", answers: ["Kumbhakarna", "Ravana", "Bali", "Meghnad"], correct: 1 },
  { question: "Who broke Shiva’s bow?", answers: ["Rama", "Arjuna", "Krishna", "Bhima"], correct: 0 },
  { question: "Who was Abhimanyu’s father?", answers: ["Arjuna", "Bhima", "Karna", "Yudhishthira"], correct: 0 },
  { question: "Who was the teacher of Pandavas and Kauravas?", answers: ["Kripacharya", "Dronacharya", "Parashurama", "Vyasa"], correct: 1 },
  { question: "Who is the son of Vayu?", answers: ["Hanuman", "Bheema", "Garuda", "Nakula"], correct: 0 },
  { question: "Which epic contains the Bhagavad Gita?", answers: ["Ramayana", "Mahabharata", "Vedas", "Puranas"], correct: 1 },
  //GK
  { question: "What is the national animal of India?", answers: ["Lion", "Tiger", "Elephant", "Leopard"], correct: 1 },
  { question: "What is the national bird of India?", answers: ["Peacock", "Eagle", "Sparrow", "Parrot"], correct: 0 },
  { question: "Who is known as the Father of the Indian Nation?", answers: ["Jawaharlal Nehru", "Sardar Patel", "Mahatma Gandhi", "Subhash Chandra Bose"], correct: 2 },
  { question: "Which is the national flower of India?", answers: ["Rose", "Lotus", "Jasmine", "Sunflower"], correct: 1 },
  { question: "Which Indian city is known as the Silicon Valley of India?", answers: ["Hyderabad", "Pune", "Bengaluru", "Chennai"], correct: 2 },
  { question: "Which is the largest state in India by area?", answers: ["Maharashtra", "Madhya Pradesh", "Rajasthan", "Uttar Pradesh"], correct: 2 },
  { question: "Which river is considered the holiest in India?", answers: ["Yamuna", "Ganga", "Godavari", "Narmada"], correct: 1 },
  { question: "Which Indian monument is one of the Seven Wonders of the World?", answers: ["Qutub Minar", "Red Fort", "Taj Mahal", "Gateway of India"], correct: 2 },
  { question: "Which Indian state has the longest coastline?", answers: ["Tamil Nadu", "Andhra Pradesh", "Maharashtra", "Gujarat"], correct: 3 },
  { question: "What is the national sport of India (as commonly believed)?", answers: ["Cricket", "Hockey", "Kabaddi", "Football"], correct: 1 },
  //BOLLYWOOD DIALOGUES
  {
    question: "Complete the dialogue: 'Rishte mein toh hum tumhare ___ lagte hain.'",
    answers: ["baap", "chacha", "dost", "bhai"],
    correct: 0,
  },
  {
    question: "Complete the dialogue: 'Zindagi mein kuch banna ho, kuch haasil karna ho, toh ___ mat haaro.'",
    answers: ["mehnat", "hausla", "himat", "dil"],
    correct: 1,
  },
  {
    question: "Complete the dialogue: 'Mogambo ___ hua.'",
    answers: ["gussa", "khush", "naraz", "hairaan"],
    correct: 1,
  },
  {
    question: "Complete the dialogue: 'Hum ek baar jeete hain, ek baar marte hain, ___ bhi ek hi baar hota hai.'",
    answers: ["dosti", "shaadi", "pyaar", "yaari"],
    correct: 2,
  },
  {
    question: "Complete the dialogue: 'Jaa Simran, ___.'",
    answers: ["bhaag ja", "jee le apni zindagi", "khush reh", "ghar ja"],
    correct: 1,
  },
  {
    question: "Complete the dialogue: 'Aaj ek ___ aur ___ ka khel hoga.'",
    answers: ["dum", "dimaag", "josh", "himat"],
    correct: 1,
  },
  {
    question: "Complete the dialogue: 'Hum jahan khade ho jaate hain, ___ wahi se shuru hoti hai.'",
    answers: ["line", "race", "competition", "kahani"],
    correct: 2,
  },
  {
    question: "Complete the dialogue: 'Ek ladki thi deewani si, ___ pe woh marti thi.'",
    answers: ["sapno", "khwabon", "baaton", "yaadon"],
    correct: 1,
  },
  {
    question: "Complete the dialogue: 'Main apni favourite hoon, kyunki main ___ hoon.'",
    answers: ["strong", "confident", "original", "khud"],
    correct: 3,
  },
  {
    question: "Complete the dialogue: 'Picture abhi ___ hai mere dost.'",
    answers: ["shuru", "chal rahi", "baaki", "adhoori"],
    correct: 2,
  },
  {
    question: "Which is the largest continent in the world?",
    answers: ["Africa", "Asia", "Europe", "North America"],
    correct: 1,
  },
  {
    question: "Which ocean is the deepest in the world?",
    answers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correct: 3,
  },
  {
    question: "Which is the longest river in the world?",
    answers: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correct: 1,
  },
  {
    question: "Which country has the longest coastline in the world?",
    answers: ["Australia", "Russia", "Canada", "USA"],
    correct: 2,
  },
  {
    question: "Which is the highest mountain peak in the world?",
    answers: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"],
    correct: 1,
  },
  {
    question: "Which desert is the largest hot desert in the world?",
    answers: ["Thar", "Gobi", "Kalahari", "Sahara"],
    correct: 3,
  },
  {
    question: "Which Indian state is known as the 'Land of Rising Sun'?",
    answers: ["Assam", "Sikkim", "Arunachal Pradesh", "Nagaland"],
    correct: 2,
  },
  {
    question: "Which latitude passes through the middle of India?",
    answers: ["Tropic of Cancer", "Equator", "Arctic Circle", "Prime Meridian"],
    correct: 0,
  },
  {
    question: "Which sea separates India and Sri Lanka?",
    answers: ["Arabian Sea", "Bay of Bengal", "Indian Ocean", "Palk Strait"],
    correct: 3,
  },
  {
    question: "Which country is known as the 'Land of the Rising Sun'?",
    answers: ["China", "South Korea", "Japan", "Thailand"],
    correct: 2,
  },
    {
    question: "Who wrote the Indian National Anthem?",
    answers: ["Bankim Chandra Chatterjee", "Rabindranath Tagore", "Sarojini Naidu", "Subhash Chandra Bose"],
    correct: 1,
  },
    {
    question: "Krishnadevaraya was the ruler of which empire?",
    answers: ["Maurya Empire", "Gupta Empire", "Vijayanagara Empire", "Chola Empire"],
    correct: 2,
  },
   {
    question: "The song 'Tum Hi Ho' is from which Bollywood movie?",
    answers: ["Aashiqui 2", "Ek Villain", "Rockstar", "Kabir Singh"],
    correct: 0,
  },
  {
    question: "The song 'Jai Ho' is from which movie?",
    answers: ["Lagaan", "Swades", "Slumdog Millionaire", "Guru"],
    correct: 2,
  },
  {
    question: "The song 'Kal Ho Naa Ho' is from which movie?",
    answers: ["Kabhi Khushi Kabhie Gham", "Kal Ho Naa Ho", "Veer-Zaara", "My Name Is Khan"],
    correct: 1,
  },
  {
    question: "The song 'Chaiyya Chaiyya' is from which movie?",
    answers: ["Dil Se", "Bombay", "Guru", "Roja"],
    correct: 0,
  },
  {
    question: "The song 'Tujhe Dekha Toh' is from which movie?",
    answers: ["Dil To Pagal Hai", "Kuch Kuch Hota Hai", "Dilwale Dulhania Le Jayenge", "Veer-Zaara"],
    correct: 2,
  },
  {
    question: "The song 'Gerua' is from which movie?",
    answers: ["Raees", "Dilwale", "Jab Tak Hai Jaan", "Fan"],
    correct: 1,
  },
  {
    question: "The song 'Zingaat' (Hindi version) is from which movie?",
    answers: ["Dhadak", "Sairat", "Loveratri", "Shubh Mangal Zyada Saavdhan"],
    correct: 0,
  },
  {
    question: "The song 'Kabira' is from which movie?",
    answers: ["Yeh Jawaani Hai Deewani", "Rockstar", "Wake Up Sid", "Tamasha"],
    correct: 0,
  },
  {
    question: "The song 'Badtameez Dil' is from which movie?",
    answers: ["Ae Dil Hai Mushkil", "Yeh Jawaani Hai Deewani", "Student of the Year", "Tamasha"],
    correct: 1,
  },
  {
    question: "The song 'Kesariya' is from which movie?",
    answers: ["Brahmāstra", "Kalank", "Rocky Aur Rani Kii Prem Kahaani", "Tu Jhoothi Main Makkaar"],
    correct: 0,
  }
];
